chore: update to use new template and conventions

diff --git a/popup-new-file-dialog b/popup-new-file-dialog
--- a/popup-new-file-dialog
+++ b/popup-new-file-dialog
@@ -1,7 +1,49 @@
 #!/bin/bash
 set -o errexit -o pipefail -o noclobber -o nounset 				#Common safety settings, useful for most scripts.
 
+help='Brings up a yad dialog. The entered text will be used to create a new file.
+Useful when bound to a shortcut inside Thunar, as Thunar does not have a keybind for this.
+
+Usage:
+    popup-new-file-dialog
+    popup-new-file-dialog -h/--help
+Options:
+    -h/--help    Show this help dialog.'
+
 #============================ Safe Guards ==============================
+#Valid Argument Counts
+min_args=0
+max_args=1				#Set to -1 for scripts that take unlimited args.
+
+#Exit Codes
+EXIT_SUCCESS=0
+EXIT_TOO_FEW_ARGS=10
+EXIT_TOO_MANY_ARGS=11
+
+if [ $# -lt $min_args ]; then
+	echo "[ERROR] Not enough arguments. Use -h for help."
+	exit $EXIT_TOO_FEW_ARGS
+fi
+
+if [ $max_args -ne -1 ] && [ $# -gt $max_args ]; then
+	echo "[ERROR] Too many arguments. Use -h for help."
+	exit $EXIT_TOO_MANY_ARGS
+fi
+
+#============================ Script Vars ==============================
+#Options
+o_help=false
+
+for arg; do
+	if   [ "$arg" == "-h" ] || [ "$arg" == "--help" ]; then o_help=true
+	fi
+done
+
+#============================ Pre-Main ==============================
+if $o_help; then
+	echo "$help"
+	exit $EXIT_SUCCESS
+fi
 
 #============================ Dialog & Parse Vars ==============================
 #Brings up a yad dialog. The entered text will be used to create a new file.
@@ -24,17 +66,16 @@ prefix_timestamp=${opts[3]}
 #echo "${opts[@]}"
 #echo $filename $repeats $append_timestamp $prefix_timestamp
 
+#============================ Main ==============================
 #If a global FDATE format is specified, used that, otherwise, use a fallback.
 fdate="${FDATE:-date +%F_%H-%M-%S}"
 date=$($fdate)
-echo $date
-
-#============================ Main =============================
+#echo $date
 
 if [ $append_timestamp == "TRUE" ]; then filename="$filename $date"; fi
 if [ $prefix_timestamp == "TRUE" ]; then filename="$date $filename"; fi
 
-echo $filename
+#echo $filename
 
 #Skip the first one from the loop and do it seperately, as it doesn't need the "($i)" suffix.
 touch "$filename"
@@ -42,3 +83,5 @@ touch "$filename"
 for ((i = 1; i < repeats; i++)); do
 	touch "$filename ($i)"
 done
+
+exit $EXIT_SUCCESS
